# Development Profile
# This file can be committed (with dummy/default values)

quarkus.datasource.username=ns
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/quarkus_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
